import { Container, Main } from "../../theme/components";
import Head from "next/head";

export default function AboutPage() {
  return (
    <Container>
      <Head>
        <title>DevXpert - Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main></Main>
    </Container>
  );
}
