import HomePage from "../src/screen/HomePage";

export default HomePage;
/*import Head from "next/head";
import { Container, Main } from "../src/theme/components";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>DevXpert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main></Main>
    </Container>
  );
}*/
