import Head from "next/head";
import { CardContainer, Container, Main } from "../../theme/components";
import Card from "../../components/Card";

export default function HomePage() {
  return (
    <Container>
      <Head>
        <title>DevXpert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <CardContainer>
          <Card
            title="Título"
            description="Esta é a descrição do card. Aqui você pode adicionar mais detalhes sobre o conteúdo."
            imageUrl="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeNtC7luurdQvpIi8yT5VygpkLONnmsU86EQ&usqp=CAU"
          />
      </CardContainer>
      </Main>
    </Container>
  );
}
